variables:
- name: COMMIT
  value: $(Build.SourceVersion)$(Build.BuildNumber)
- name: SERVICE_NAME
  value: facebookservice
- name: pathToCache
  value: $(Pipeline.Workspace)/.m2/repository
- name: cacheKey
  value: maven | "$(Agent.OS)" | **/pom.xml
- name: restoreKeys
  value: ' | maven | "$(Agent.OS)" maven '
- name: PMD_ANALYSIS_SKIP
  value: false
- name: JUNIT_TESTS_ANALYSIS_SKIP
  value: false
- name: BUILD_QUALITYCHECK
  value: false
- name: SONAR_ANALYSIS
  value: true
resources:
  repositories:
  - repository: self
    type: git
    ref: azure-pipelines
name: $(date:yyyyMMdd)$(rev:.r)
trigger: none
pr: none
pool:
  name: kubernetes

steps:
  - script:  echo "HOSTNAME"